return {
	Title = "[PT-BR] Otimização",
	Author = "Yuri",
	Description = "Melhora a fluidez do jogo e algumas lógicas de operação. Todas as opções de otimização podem ser ativadas ou desativadas conforme desejado.\r\n\r\nOtimizações:\r\n* Carregamento das fotos dos personagens de forma gradual em vez de instantânea. Se não gostar do efeito de transição, pode configurar para mostrar imediatamente.\r\n* Abertura mais rápida da janela de diálogo e mudança do estilo: de descer para aparecer suavemente.\r\n* Adicionada novamente a exibição do alcance de ataque na tela de batalha.\r\n* 【Necessário ativar manualmente】 Acelerar o tempo das animações na conclusão das batalhas.\r\n* Otimizada a maneira de caminhar nas aventuras, sem mais parar a cada passo.\r\n* 【Necessário ativar manualmente】 Acelerar a velocidade de movimento nas aventuras.\r\n* 【Necessário ativar manualmente】 Acelerar a velocidade de abertura das áreas nas aventuras.\r\n* Otimizada a movimentação no mapa principal.\r\n* 【Necessário ativar manualmente】 Acelerar a velocidade de movimentação no mapa principal.\r\r\n\r\nPara discutir o mod, reportar bugs ou solicitar atualizações, junte-se ao Discord: \n- https://discord.com/invite/aYbWBr4",
	Cover = "Cover.png",
	FileId = 1,
	GameVersion = "0.0.72.14",
	Source = 0,
	FrontendPlugins = {
		[1] = "TaiwuOptimize.dll",
	},
	BackendPlugins = {
		[1] = "TaiwuOptimizeBackend.dll",
	},
	DefaultSettings = {
		[1] = {
			SettingType = "Toggle",
			Key = "Bool_EnableAvatarDelayRefresh",
			DisplayName = "Carregamento atrasado de avatar",
			Description = "Carregar avatares de forma atrasada para reduzir travamentos ao carregar muitos avatares.",
			DefaultValue = true,
		},
		[2] = {
			SettingType = "Dropdown",
			Key = "Int_AvatarFadeInTimeTypeR",
			DisplayName = "Tempo de fade-in do avatar",
			Description = "<color=#FF0000>[Necessário ativar carregamento atrasado de avatar]</color> Tempo de fade-in após carregar o avatar. Se não gostar do efeito de fade, pode configurar para [exibição imediata]",
			Options = {
				[1] = "Exibição imediata",
				[2] = "0.3 segundos",
				[3] = "0.5 segundos",
				[4] = "1 segundo",
			},
			DefaultValue = 0,
		},
		[3] = {
			SettingType = "Toggle",
			Key = "Bool_EnableEventWindowFade",
			DisplayName = "Usar fade-in na janela de diálogo",
			Description = "Mudar a animação da janela de diálogo para fade-in.",
			DefaultValue = true,
		},
		[4] = {
			SettingType = "Dropdown",
			Key = "Int_EventWindowFadeTimeType",
			DisplayName = "Tempo de animação da janela de diálogo",
			Description = "Tempo da animação de aparecimento da janela de diálogo.",
			Options = {
				[1] = "0.3 segundos",
				[2] = "0.5 segundos",
				[3] = "1 segundo",
				[4] = "Exibição imediata",
			},
			DefaultValue = 0,
		},
		[5] = {
			SettingType = "Toggle",
			Key = "Bool_EnableCombatRange",
			DisplayName = "Mostrar alcance de ataque",
			Description = "Mostrar o alcance de ataque embaixo do personagem durante a batalha.",
			DefaultValue = true,
		},
		[6] = {
			SettingType = "Dropdown",
			Key = "Int_CombatResultAnimScaleType",
			DisplayName = "Velocidade da animação de conclusão da batalha",
			Description = "Velocidade da animação na tela de conclusão da batalha.",
			Options = {
				[1] = "1x",
				[2] = "1.25x",
				[3] = "1.5x",
				[4] = "1.75x",
				[5] = "2x (recomendado)",
				[6] = "3x",
				[7] = "4x",
				[8] = "5x",
			},
			DefaultValue = 4,
		},
		[7] = {
			SettingType = "Toggle",
			Key = "Bool_EnableQuickAdventure",
			DisplayName = "Otimização de movimento em aventuras",
			Description = "Tornar o movimento em aventuras mais fluido (sem parar a cada passo).",
			DefaultValue = true,
		},
		[8] = {
			SettingType = "Toggle",
			Key = "Bool_EnableAdventureCameraFollow",
			DisplayName = "Câmera segue nas aventuras",
			Description = "Faz com que a câmera siga o personagem durante o movimento nas aventuras.",
			DefaultValue = true,
		},
		[9] = {
			SettingType = "Dropdown",
			Key = "Int_AdventureMoveSpeedScaleType",
			DisplayName = "Velocidade de movimento nas aventuras",
			Description = "Velocidade de movimento na interface de aventuras.",
			Options = {
				[1] = "1x",
				[2] = "1.25x",
				[3] = "1.5x (recomendado)",
				[4] = "1.75x",
				[5] = "2x",
				[6] = "3x",
				[7] = "4x",
				[8] = "5x",
			},
			DefaultValue = 2,
		},
		[10] = {
			SettingType = "Dropdown",
			Key = "Int_AdventureUnfoldAnimationTimeScaleType",
			DisplayName = "Velocidade de expansão nas aventuras",
			Description = "Velocidade de expansão dos quadrados na interface de aventuras.",
			Options = {
				[1] = "1x",
				[2] = "1.25x",
				[3] = "1.5x (recomendado)",
				[4] = "1.75x",
				[5] = "2x",
				[6] = "3x",
				[7] = "4x",
				[8] = "5x",
			},
			DefaultValue = 2,
		},
		[11] = {
			SettingType = "Toggle",
			Key = "Bool_EnableQuickWorldMapMove",
			DisplayName = "Otimização de movimento no mapa-múndi",
			Description = "Otimiza o movimento no mapa-múndi para ser mais fluido.",
			DefaultValue = true,
		},
		[12] = {
			SettingType = "Toggle",
			Key = "Bool_EnableLinerWorldMapMove",
			DisplayName = "Movimento linear no mapa-múndi",
			Description = "<color=#FF0000>[Necessário ativar otimização de movimento no mapa-múndi]</color> Torna o movimento no mapa-múndi uma animação linear, mais fluida em movimentos contínuos.",
			DefaultValue = true,
		},
		[13] = {
			SettingType = "Dropdown",
			Key = "Int_WorldMapMoveSpeedScaleType",
			DisplayName = "Velocidade de movimento no mapa-múndi",
			Description = "<color=#FF0000>[Necessário ativar otimização de movimento no mapa-múndi]</color> Velocidade de movimento no mapa-múndi.",
			Options = {
				[1] = "1x",
				[2] = "1.25x (recomendado)",
				[3] = "1.5x",
				[4] = "1.75x",
				[5] = "2x",
				[6] = "3x",
				[7] = "4x",
				[8] = "5x",
			},
			DefaultValue = 1,
		},
	},
	Version = "1.0.0.1",
	WorkshopCover = "OTIMIZACAO DE TAIWU.png",
	TagList = {
		[1] = "Optimizations",
		[2] = "Compatible Mods",
	},
	Visibility = 0,
	UpdateLogList = {
		[1] = {
			Timestamp = 1714207966,
		},
		[2] = {
			Timestamp = 1714208664,
		},
		[3] = {
			Timestamp = 1723092208,
		},
		[4] = {
			Timestamp = 1723093470,
		},
	},
	ChangeConfig = false,
	HasArchive = false,
	NeedRestartWhenSettingChanged = false,
}
